/**
 * Catálogo oficial del seed de desarrollo. Fuente única para `db:seed` y
 * `db:seed:mega` — evita SKUs fantasma en el mega-seed.
 */
export const PRODUCTOS_SEED = [
  {
    sku: "TORT-16",
    nombreCanonico: "Tortillas #16",
    familia: "TORTILLA" as const,
    unidadMedida: "LIBRA" as const,
    puntoCarga: "DEMOCRACIA" as const,
    esProducido: true,
    orden: 1,
  },
  {
    sku: "TORT-14",
    nombreCanonico: "Tortillas #14",
    familia: "TORTILLA" as const,
    unidadMedida: "LIBRA" as const,
    puntoCarga: "DEMOCRACIA" as const,
    esProducido: true,
    orden: 2,
  },
  {
    sku: "TORT-12",
    nombreCanonico: "Tortillas #12",
    familia: "TORTILLA" as const,
    unidadMedida: "LIBRA" as const,
    puntoCarga: "DEMOCRACIA" as const,
    esProducido: true,
    orden: 3,
  },
  {
    sku: "TORT-10",
    nombreCanonico: "Tortillas #10",
    familia: "TORTILLA" as const,
    unidadMedida: "LIBRA" as const,
    puntoCarga: "DEMOCRACIA" as const,
    esProducido: true,
    orden: 4,
  },
  {
    sku: "TORT-GARN",
    nombreCanonico: "Tortillas para Garnachas",
    familia: "TORTILLA" as const,
    unidadMedida: "LIBRA" as const,
    puntoCarga: "DEMOCRACIA" as const,
    esProducido: true,
    orden: 5,
  },
  {
    sku: "NACH-B-P",
    nombreCanonico: "Nachos Blancos Pequeños",
    familia: "FRITURA" as const,
    unidadMedida: "BOLSA" as const,
    puntoCarga: "PLANTA" as const,
    esProducido: true,
    orden: 6,
  },
  {
    sku: "NACH-B-G",
    nombreCanonico: "Nachos Blancos Grandes",
    familia: "FRITURA" as const,
    unidadMedida: "BOLSA" as const,
    puntoCarga: "PLANTA" as const,
    esProducido: true,
    orden: 7,
  },
  {
    sku: "NACH-A-G",
    nombreCanonico: "Nachos Amarillos Grandes",
    familia: "FRITURA" as const,
    unidadMedida: "BOLSA" as const,
    puntoCarga: "PLANTA" as const,
    esProducido: true,
    orden: 8,
  },
  {
    sku: "PAL-B",
    nombreCanonico: "Palitos Blancos",
    familia: "FRITURA" as const,
    unidadMedida: "BOLSA" as const,
    puntoCarga: "PLANTA" as const,
    esProducido: true,
    orden: 9,
  },
  {
    sku: "PAL-A",
    nombreCanonico: "Palitos Amarillos",
    familia: "FRITURA" as const,
    unidadMedida: "BOLSA" as const,
    puntoCarga: "PLANTA" as const,
    esProducido: true,
    orden: 10,
  },
  {
    sku: "FAJ-B",
    nombreCanonico: "Fajitas Blancas",
    familia: "FRITURA" as const,
    unidadMedida: "BOLSA" as const,
    puntoCarga: "PLANTA" as const,
    esProducido: true,
    orden: 11,
  },
  {
    sku: "PAPA-S-P",
    nombreCanonico: "Papalinas Saladas Pequeñas",
    familia: "FRITURA" as const,
    unidadMedida: "BOLSA" as const,
    puntoCarga: "PLANTA" as const,
    esProducido: true,
    orden: 12,
  },
  {
    sku: "PAPA-BBQ-P",
    nombreCanonico: "Papalinas Barbacoa Pequeñas",
    familia: "FRITURA" as const,
    unidadMedida: "BOLSA" as const,
    puntoCarga: "PLANTA" as const,
    esProducido: true,
    orden: 13,
  },
  {
    sku: "PAPA-S-G",
    nombreCanonico: "Papalinas Saladas Grandes",
    familia: "FRITURA" as const,
    unidadMedida: "BOLSA" as const,
    puntoCarga: "PLANTA" as const,
    esProducido: true,
    orden: 14,
  },
  {
    sku: "PAPA-BBQ-G",
    nombreCanonico: "Papalinas Barbacoa Grandes",
    familia: "FRITURA" as const,
    unidadMedida: "BOLSA" as const,
    puntoCarga: "PLANTA" as const,
    esProducido: true,
    orden: 15,
  },
  {
    sku: "TOST-16-B",
    nombreCanonico: "Tostadas #16 Blancas",
    familia: "TOSTADA" as const,
    unidadMedida: "BOLSA" as const,
    puntoCarga: "PLANTA" as const,
    esProducido: true,
    orden: 16,
  },
  {
    sku: "TOST-13-B",
    nombreCanonico: "Tostadas #13 Blancas",
    familia: "TOSTADA" as const,
    unidadMedida: "BOLSA" as const,
    puntoCarga: "PLANTA" as const,
    esProducido: true,
    orden: 17,
  },
  {
    sku: "TOST-12-B",
    nombreCanonico: "Tostadas #12 Blancas",
    familia: "TOSTADA" as const,
    unidadMedida: "BOLSA" as const,
    puntoCarga: "PLANTA" as const,
    esProducido: true,
    orden: 18,
  },
  {
    sku: "TOST-BOQ",
    nombreCanonico: "Tostadas para Boquitas (PIZZEROLAS)",
    familia: "TOSTADA" as const,
    unidadMedida: "BOLSA" as const,
    puntoCarga: "PLANTA" as const,
    esProducido: true,
    orden: 19,
  },
  {
    sku: "CANAST-A",
    nombreCanonico: "Canastitas Amarillas",
    familia: "TOSTADA" as const,
    unidadMedida: "BOLSA" as const,
    puntoCarga: "PLANTA" as const,
    esProducido: true,
    orden: 20,
  },
] as const;

export type ProductoSeed = (typeof PRODUCTOS_SEED)[number];
