/** Catálogo de demo para el mega-seed (precios de prueba, no reales). */

export const PRECIOS_DEMO_CENTAVOS: Record<string, number> = {
  "TORT-16": 1250,
  "TORT-14": 1100,
  "TORT-12": 1000,
  "TORT-10": 900,
  "TORT-GARN": 1200,
  "NACH-B-P": 1000,
  "NACH-B-G": 1800,
  "NACH-A-G": 1800,
  "PAL-B": 1200,
  "PAL-A": 1200,
  "FAJ-B": 1600,
  "PAPA-S-P": 600,
  "PAPA-BBQ-P": 600,
  "PAPA-S-G": 1400,
  "PAPA-BBQ-G": 1400,
  "TOST-16-B": 2000,
  "TOST-13-B": 1800,
  "TOST-12-B": 1500,
  "TOST-BOQ": 1400,
  "CANAST-A": 1200,
  "TOST-G": 1800,
  "TOST-P": 1500,
  "NACH-B": 1500,
  "NACH-A": 1500,
  "PAPA-S": 1400,
  "PAPA-BBQ": 1400,
  FAJITA: 1600,
};

export const ALIAS_DEMO: Record<string, string> = {
  "TORT-16": "tortilla #16",
  "TORT-14": "tortilla #14",
  "TORT-12": "tortilla #12",
  "TORT-10": "tortilla #10",
  "TORT-GARN": "tortilla garnacha",
  "NACH-B-P": "nachos blancos pequeños",
  "NACH-B-G": "nachos blancos grandes",
  "NACH-A-G": "nachos amarillos grandes",
  "PAL-B": "palitos blancos",
  "PAL-A": "palitos amarillos",
  "FAJ-B": "fajitas blancas",
  "PAPA-S-P": "papalinas saladas pequeñas",
  "PAPA-BBQ-P": "papalinas barbacoa pequeñas",
  "PAPA-S-G": "papalinas saladas grandes",
  "PAPA-BBQ-G": "papalinas barbacoa grandes",
  "TOST-16-B": "tostadas #16 blancas",
  "TOST-13-B": "tostadas #13 blancas",
  "TOST-12-B": "tostadas #12 blancas",
  "TOST-BOQ": "tostadas boquitas",
  "CANAST-A": "canastitas amarillas",
  "TOST-G": "tostada grande",
  "TOST-P": "tostada chica",
  "NACH-B": "nachos blancos",
  "NACH-A": "nachos amarillos",
  "PAPA-S": "papalinas",
  "PAPA-BBQ": "papalinas BBQ",
  FAJITA: "fajitas",
};

export type PerfilCliente =
  | "diario"
  | "semanal"
  | "ocasional"
  | "moroso"
  | "transferencia"
  | "inactivo";

export type ClienteMegaDef = {
  nombre: string;
  contacto: string;
  perfil: PerfilCliente;
  limiteFacturasPendientes: number | null;
  horarioEntregaFijo: string | null;
  notas: string;
  /** SKUs favoritos; si vacío se eligen al azar. */
  skusPreferidos?: string[];
};

/** ~45 restaurantes guatemaltecos ficticios para llenar listas y cartera. */
export const CLIENTES_MEGA: ClienteMegaDef[] = [
  {
    nombre: "El Portal de Antigua",
    contacto: "Doña Marta",
    perfil: "diario",
    limiteFacturasPendientes: 5,
    horarioEntregaFijo: "07:30",
    notas: "Entrega temprana. Pide tortillas todos los días.",
    skusPreferidos: ["TORT-16", "TORT-14", "TOST-G"],
  },
  {
    nombre: "Cantina Los Arcos",
    contacto: "Don Julio",
    perfil: "diario",
    limiteFacturasPendientes: 4,
    horarioEntregaFijo: "08:00",
    notas: "Ruta Democracia.",
    skusPreferidos: ["TORT-16", "NACH-B", "PAL-A"],
  },
  {
    nombre: "Pupusería El Comal",
    contacto: "Ana López",
    perfil: "diario",
    limiteFacturasPendientes: 3,
    horarioEntregaFijo: "06:45",
    notas: "Solo tortillas. Grosor especial.",
    skusPreferidos: ["TORT-16", "TORT-14", "TORT-12"],
  },
  {
    nombre: "Restaurante Vista Hermosa",
    contacto: "Chef Pablo",
    perfil: "diario",
    limiteFacturasPendientes: 6,
    horarioEntregaFijo: "09:00",
    notas: "Pedidos grandes de fin de semana.",
    skusPreferidos: ["TORT-16", "TOST-G", "NACH-A", "PAPA-S"],
  },
  {
    nombre: "Taquería El Güero",
    contacto: "Luis Méndez",
    perfil: "diario",
    limiteFacturasPendientes: 4,
    horarioEntregaFijo: "07:00",
    notas: "Paga mixto efectivo/transferencia.",
    skusPreferidos: ["TORT-14", "TORT-12", "FAJITA"],
  },
  {
    nombre: "Café Barista Zona 10",
    contacto: "Sofía Ruiz",
    perfil: "semanal",
    limiteFacturasPendientes: 2,
    horarioEntregaFijo: "10:00",
    notas: "Pide martes y viernes.",
    skusPreferidos: ["TOST-P", "NACH-B"],
  },
  {
    nombre: "Mariscos El Capitán",
    contacto: "Capitán Rojas",
    perfil: "semanal",
    limiteFacturasPendientes: 3,
    horarioEntregaFijo: "11:00",
    notas: "Solo tostadas para ceviche.",
    skusPreferidos: ["TOST-G", "TOST-P"],
  },
  {
    nombre: "Pollo Campero Express Mixco",
    contacto: "Gerente turno",
    perfil: "diario",
    limiteFacturasPendientes: 8,
    horarioEntregaFijo: "05:30",
    notas: "Volumen alto. Coordinar con planta.",
    skusPreferidos: ["TORT-16", "TORT-14", "TORT-12", "TOST-G"],
  },
  {
    nombre: "Antojitos Doña Chus",
    contacto: "Doña Chus",
    perfil: "diario",
    limiteFacturasPendientes: 2,
    horarioEntregaFijo: "06:00",
    notas: "Efectivo siempre.",
    skusPreferidos: ["TORT-14", "PAL-B", "PAPA-BBQ"],
  },
  {
    nombre: "Sushi Sakura Cayalá",
    contacto: "Kenji",
    perfil: "ocasional",
    limiteFacturasPendientes: 2,
    horarioEntregaFijo: "14:00",
    notas: "Pedidos esporádicos para eventos.",
    skusPreferidos: ["TOST-P", "NACH-A"],
  },
  {
    nombre: "Steak House El Roble",
    contacto: "Mario Estrada",
    perfil: "semanal",
    limiteFacturasPendientes: 4,
    horarioEntregaFijo: "10:30",
    notas: "Nachos y papalinas para bar.",
    skusPreferidos: ["NACH-B", "NACH-A", "PAPA-S", "PAPA-BBQ"],
  },
  {
    nombre: "Comedor Popular La Esperanza",
    contacto: "Doña Esperanza",
    perfil: "diario",
    limiteFacturasPendientes: 3,
    horarioEntregaFijo: "05:45",
    notas: "Precio sensible. Tortilla chica.",
    skusPreferidos: ["TORT-12", "TORT-14"],
  },
  {
    nombre: "Bar Deportivo 90 Minutos",
    contacto: "Chino",
    perfil: "semanal",
    limiteFacturasPendientes: 5,
    horarioEntregaFijo: "16:00",
    notas: "Picos en días de fútbol.",
    skusPreferidos: ["NACH-B", "PAL-A", "PAPA-BBQ", "FAJITA"],
  },
  {
    nombre: "Hotel Clarion Suite",
    contacto: "Banquetes",
    perfil: "ocasional",
    limiteFacturasPendientes: 10,
    horarioEntregaFijo: "08:30",
    notas: "Factura a nombre del hotel.",
    skusPreferidos: ["TORT-16", "TOST-G", "NACH-B"],
  },
  {
    nombre: "Tacos El Norteño",
    contacto: "José Ramírez",
    perfil: "diario",
    limiteFacturasPendientes: 4,
    horarioEntregaFijo: "07:15",
    notas: "Quiere fajitas los jueves.",
    skusPreferidos: ["TORT-16", "FAJITA", "PAL-B"],
  },
  {
    nombre: "Cevichería Puerto Azul",
    contacto: "Andrea Soto",
    perfil: "diario",
    limiteFacturasPendientes: 3,
    horarioEntregaFijo: "09:30",
    notas: "Tostada grande predominante.",
    skusPreferidos: ["TOST-G", "TOST-P"],
  },
  {
    nombre: "Panadería San Martín",
    contacto: "Don Martín",
    perfil: "semanal",
    limiteFacturasPendientes: 2,
    horarioEntregaFijo: "06:30",
    notas: "Complemento de desayunos.",
    skusPreferidos: ["TORT-14", "TOST-P"],
  },
  {
    nombre: "Food Court Oakland Mall",
    contacto: "Operaciones",
    perfil: "diario",
    limiteFacturasPendientes: 7,
    horarioEntregaFijo: "08:00",
    notas: "Varios locales. Consolidar en una entrega.",
    skusPreferidos: ["TORT-16", "TORT-14", "NACH-B", "NACH-A", "PAPA-S"],
  },
  {
    nombre: "Rincón Chapín",
    contacto: "Patricia",
    perfil: "diario",
    limiteFacturasPendientes: 3,
    horarioEntregaFijo: "07:45",
    notas: "Cliente fiel desde hace años.",
    skusPreferidos: ["TORT-16", "TORT-12", "PAL-A"],
  },
  {
    nombre: "La Casa del Churrasco",
    contacto: "Don Beto",
    perfil: "semanal",
    limiteFacturasPendientes: 4,
    horarioEntregaFijo: "11:30",
    notas: "Pedidos de fin de semana más grandes.",
    skusPreferidos: ["TORT-16", "TOST-G", "NACH-A"],
  },
  {
    nombre: "Heladería Frosty",
    contacto: "Karen",
    perfil: "ocasional",
    limiteFacturasPendientes: 1,
    horarioEntregaFijo: "12:00",
    notas: "Casi no pide; mantener en catálogo.",
    skusPreferidos: ["TOST-P"],
  },
  {
    nombre: "Trattoria Bella Italia",
    contacto: "Giuseppe",
    perfil: "semanal",
    limiteFacturasPendientes: 3,
    horarioEntregaFijo: "10:00",
    notas: "Tostadas para antipasti.",
    skusPreferidos: ["TOST-G", "TOST-P"],
  },
  {
    nombre: "Churrasquería Gaucha",
    contacto: "Rodrigo",
    perfil: "diario",
    limiteFacturasPendientes: 5,
    horarioEntregaFijo: "08:15",
    notas: "Volumen medio-alto.",
    skusPreferidos: ["TORT-16", "TORT-14", "PAPA-S"],
  },
  {
    nombre: "Snack Zone Universidad",
    contacto: "Estudiante encargado",
    perfil: "diario",
    limiteFacturasPendientes: 2,
    horarioEntregaFijo: "09:00",
    notas: "Frituras y nachos.",
    skusPreferidos: ["NACH-B", "PAL-B", "PAPA-BBQ", "FAJITA"],
  },
  {
    nombre: "Asados El Quetzal",
    contacto: "Don Quique",
    perfil: "moroso",
    limiteFacturasPendientes: 2,
    horarioEntregaFijo: "10:00",
    notas: "Histórico de atraso. Vigilar cartera.",
    skusPreferidos: ["TORT-16", "TOST-G", "NACH-A"],
  },
  {
    nombre: "Cafetería Municipal",
    contacto: "Lic. Herrera",
    perfil: "moroso",
    limiteFacturasPendientes: 2,
    horarioEntregaFijo: "07:00",
    notas: "Pago lento por trámite interno.",
    skusPreferidos: ["TORT-14", "TORT-12"],
  },
  {
    nombre: "Disco Lounge Neon",
    contacto: "DJ Mike",
    perfil: "moroso",
    limiteFacturasPendientes: 3,
    horarioEntregaFijo: "17:00",
    notas: "Muchas facturas abiertas a propósito (prueba).",
    skusPreferidos: ["NACH-B", "NACH-A", "PAPA-BBQ", "PAL-A"],
  },
  {
    nombre: "Buffet El Dorado",
    contacto: "Contabilidad",
    perfil: "transferencia",
    limiteFacturasPendientes: 6,
    horarioEntregaFijo: "06:00",
    notas: "Solo transferencia. Nunca efectivo.",
    skusPreferidos: ["TORT-16", "TORT-14", "TOST-G", "TOST-P"],
  },
  {
    nombre: "Empresa Catering Alfa",
    contacto: "Compras",
    perfil: "transferencia",
    limiteFacturasPendientes: 8,
    horarioEntregaFijo: "05:00",
    notas: "OC previa. Transferencia semanal.",
    skusPreferidos: ["TORT-16", "NACH-B", "PAPA-S", "FAJITA"],
  },
  {
    nombre: "Hospital Centro Médico (cafetería)",
    contacto: "Nutrición",
    perfil: "transferencia",
    limiteFacturasPendientes: 5,
    horarioEntregaFijo: "05:15",
    notas: "Facturación institucional.",
    skusPreferidos: ["TORT-14", "TORT-12", "TOST-P"],
  },
  {
    nombre: "Colegio Monte Verde (comedor)",
    contacto: "Administración",
    perfil: "transferencia",
    limiteFacturasPendientes: 4,
    horarioEntregaFijo: "06:00",
    notas: "Lunes a viernes lectivos.",
    skusPreferidos: ["TORT-14", "TORT-12"],
  },
  {
    nombre: "Pastelería Dulce Encanto",
    contacto: "María Fernanda",
    perfil: "ocasional",
    limiteFacturasPendientes: 2,
    horarioEntregaFijo: "11:00",
    notas: "Eventos y pedidos especiales.",
    skusPreferidos: ["TOST-P", "PAL-B"],
  },
  {
    nombre: "Burger Lab Zona 4",
    contacto: "Alex Chef",
    perfil: "diario",
    limiteFacturasPendientes: 4,
    horarioEntregaFijo: "10:45",
    notas: "Tortilla para wraps.",
    skusPreferidos: ["TORT-16", "TORT-14"],
  },
  {
    nombre: "Poke Bowl Ocean",
    contacto: "Nicole",
    perfil: "semanal",
    limiteFacturasPendientes: 2,
    horarioEntregaFijo: "12:30",
    notas: "Tostada chica como base.",
    skusPreferidos: ["TOST-P"],
  },
  {
    nombre: "Wings & Beer Corner",
    contacto: "Tommy",
    perfil: "diario",
    limiteFacturasPendientes: 5,
    horarioEntregaFijo: "15:00",
    notas: "Frituras para happy hour.",
    skusPreferidos: ["NACH-A", "PAL-A", "PAPA-BBQ", "FAJITA"],
  },
  {
    nombre: "Taquería 3 Hermanos",
    contacto: "Los hermanos",
    perfil: "diario",
    limiteFacturasPendientes: 3,
    horarioEntregaFijo: "06:20",
    notas: "Tres locales, una cuenta.",
    skusPreferidos: ["TORT-16", "TORT-14", "TORT-12", "FAJITA"],
  },
  {
    nombre: "Rest. Chapinlandia",
    contacto: "Doña Lili",
    perfil: "diario",
    limiteFacturasPendientes: 4,
    horarioEntregaFijo: "07:10",
    notas: "Cliente de planta.",
    skusPreferidos: ["TORT-16", "TOST-G", "PAL-B"],
  },
  {
    nombre: "Mercado Central — Puesto 42",
    contacto: "Doña Rosa",
    perfil: "diario",
    limiteFacturasPendientes: 2,
    horarioEntregaFijo: "05:00",
    notas: "Efectivo diario al entregar.",
    skusPreferidos: ["TORT-14", "TORT-12"],
  },
  {
    nombre: "Food Truck El Tornillo",
    contacto: "Memo",
    perfil: "semanal",
    limiteFacturasPendientes: 2,
    horarioEntregaFijo: null,
    notas: "Horario variable según evento.",
    skusPreferidos: ["TORT-16", "NACH-B", "FAJITA"],
  },
  {
    nombre: "Club Deportivo Los Proceres",
    contacto: "Bar del club",
    perfil: "semanal",
    limiteFacturasPendientes: 3,
    horarioEntregaFijo: "16:30",
    notas: "Torneos = picos de demanda.",
    skusPreferidos: ["NACH-B", "PAPA-S", "PAL-A"],
  },
  {
    nombre: "Ex Salón de Té Aurora",
    contacto: "—",
    perfil: "inactivo",
    limiteFacturasPendientes: null,
    horarioEntregaFijo: null,
    notas: "Dejó de pedir. Mantener histórico.",
    skusPreferidos: ["TOST-P"],
  },
  {
    nombre: "Ex Comedor El Puente",
    contacto: "—",
    perfil: "inactivo",
    limiteFacturasPendientes: null,
    horarioEntregaFijo: null,
    notas: "Cerró el local. Cliente inactivo.",
    skusPreferidos: ["TORT-14"],
  },
  {
    nombre: "Ceviches Zona Viva",
    contacto: "Fernando",
    perfil: "diario",
    limiteFacturasPendientes: 4,
    horarioEntregaFijo: "10:15",
    notas: "Alta rotación de tostada.",
    skusPreferidos: ["TOST-G", "TOST-P", "NACH-B"],
  },
  {
    nombre: "Grill House Petapa",
    contacto: "Don Chepe",
    perfil: "moroso",
    limiteFacturasPendientes: 2,
    horarioEntregaFijo: "09:45",
    notas: "Abonos parciales frecuentes.",
    skusPreferidos: ["TORT-16", "NACH-A", "PAPA-BBQ"],
  },
  {
    nombre: "Cafetería Biblioteca Nacional",
    contacto: "Concesión",
    perfil: "transferencia",
    limiteFacturasPendientes: 3,
    horarioEntregaFijo: "07:30",
    notas: "Pago quincenal por transferencia.",
    skusPreferidos: ["TORT-12", "TOST-P"],
  },
];

export const CONTACTOS_BASE_ENRICH = [
  "Tabasco Casa Vieja",
  "Tabasco Interplaza",
  "Kraken",
  "Victorias",
  "Buen Camarón",
  "Pura Frescura",
  "Metroplaza",
  "Don Napo",
  "14 Avenida",
] as const;
